<?php

namespace Database\Seeders;

use App\Models\Drug;
use Illuminate\Database\Seeder;

class DrugSeeder extends Seeder
{
    /**
     * Seed common drug records for Version 1.
     */
    public function run(): void
    {
        $drugs = [
            ['generic_name' => 'Paracetamol', 'brand_name' => null, 'drug_class' => 'Analgesic', 'dosage_form' => 'Tablet', 'strength' => null],
            ['generic_name' => 'Ibuprofen', 'brand_name' => null, 'drug_class' => 'NSAID', 'dosage_form' => 'Tablet', 'strength' => null],
            ['generic_name' => 'Aspirin', 'brand_name' => null, 'drug_class' => 'Antiplatelet / NSAID', 'dosage_form' => 'Tablet', 'strength' => null],
            ['generic_name' => 'Warfarin', 'brand_name' => null, 'drug_class' => 'Anticoagulant', 'dosage_form' => 'Tablet', 'strength' => null],
            ['generic_name' => 'Metformin', 'brand_name' => null, 'drug_class' => 'Antidiabetic', 'dosage_form' => 'Tablet', 'strength' => null],
            ['generic_name' => 'Amlodipine', 'brand_name' => null, 'drug_class' => 'Calcium channel blocker', 'dosage_form' => 'Tablet', 'strength' => null],
            ['generic_name' => 'Losartan', 'brand_name' => null, 'drug_class' => 'ARB', 'dosage_form' => 'Tablet', 'strength' => null],
            ['generic_name' => 'Enalapril', 'brand_name' => null, 'drug_class' => 'ACE inhibitor', 'dosage_form' => 'Tablet', 'strength' => null],
            ['generic_name' => 'Omeprazole', 'brand_name' => null, 'drug_class' => 'Proton pump inhibitor', 'dosage_form' => 'Capsule', 'strength' => null],
            ['generic_name' => 'Clopidogrel', 'brand_name' => null, 'drug_class' => 'Antiplatelet', 'dosage_form' => 'Tablet', 'strength' => null],
            ['generic_name' => 'Amoxicillin', 'brand_name' => null, 'drug_class' => 'Penicillin antibiotic', 'dosage_form' => 'Capsule', 'strength' => null],
            ['generic_name' => 'Azithromycin', 'brand_name' => null, 'drug_class' => 'Macrolide antibiotic', 'dosage_form' => 'Tablet', 'strength' => null],
            ['generic_name' => 'Ciprofloxacin', 'brand_name' => null, 'drug_class' => 'Fluoroquinolone antibiotic', 'dosage_form' => 'Tablet', 'strength' => null],
            ['generic_name' => 'Metronidazole', 'brand_name' => null, 'drug_class' => 'Nitroimidazole antibiotic', 'dosage_form' => 'Tablet', 'strength' => null],
            ['generic_name' => 'Diclofenac', 'brand_name' => null, 'drug_class' => 'NSAID', 'dosage_form' => 'Tablet', 'strength' => null],
            ['generic_name' => 'Atorvastatin', 'brand_name' => null, 'drug_class' => 'Statin', 'dosage_form' => 'Tablet', 'strength' => null],
            ['generic_name' => 'Simvastatin', 'brand_name' => null, 'drug_class' => 'Statin', 'dosage_form' => 'Tablet', 'strength' => null],
            ['generic_name' => 'Carbamazepine', 'brand_name' => null, 'drug_class' => 'Antiepileptic', 'dosage_form' => 'Tablet', 'strength' => null],
            ['generic_name' => 'Phenytoin', 'brand_name' => null, 'drug_class' => 'Antiepileptic', 'dosage_form' => 'Capsule', 'strength' => null],
            ['generic_name' => 'Insulin', 'brand_name' => null, 'drug_class' => 'Antidiabetic', 'dosage_form' => 'Injection', 'strength' => null],

            ['generic_name' => 'Nifedipine', 'brand_name' => null, 'drug_class' => 'Calcium channel blocker', 'dosage_form' => 'Tablet', 'strength' => null],
            ['generic_name' => 'Lisinopril', 'brand_name' => null, 'drug_class' => 'ACE inhibitor', 'dosage_form' => 'Tablet', 'strength' => null],
            ['generic_name' => 'Valsartan', 'brand_name' => null, 'drug_class' => 'ARB', 'dosage_form' => 'Tablet', 'strength' => null],
            ['generic_name' => 'Atenolol', 'brand_name' => null, 'drug_class' => 'Beta blocker', 'dosage_form' => 'Tablet', 'strength' => null],
            ['generic_name' => 'Metoprolol', 'brand_name' => null, 'drug_class' => 'Beta blocker', 'dosage_form' => 'Tablet', 'strength' => null],
            ['generic_name' => 'Carvedilol', 'brand_name' => null, 'drug_class' => 'Beta blocker', 'dosage_form' => 'Tablet', 'strength' => null],
            ['generic_name' => 'Hydralazine', 'brand_name' => null, 'drug_class' => 'Vasodilator', 'dosage_form' => 'Tablet', 'strength' => null],
            ['generic_name' => 'Methyldopa', 'brand_name' => null, 'drug_class' => 'Antihypertensive', 'dosage_form' => 'Tablet', 'strength' => null],
            ['generic_name' => 'Furosemide', 'brand_name' => null, 'drug_class' => 'Loop diuretic', 'dosage_form' => 'Tablet', 'strength' => null],
            ['generic_name' => 'Hydrochlorothiazide', 'brand_name' => null, 'drug_class' => 'Thiazide diuretic', 'dosage_form' => 'Tablet', 'strength' => null],
            ['generic_name' => 'Spironolactone', 'brand_name' => null, 'drug_class' => 'Potassium-sparing diuretic', 'dosage_form' => 'Tablet', 'strength' => null],
            ['generic_name' => 'Potassium chloride', 'brand_name' => null, 'drug_class' => 'Electrolyte supplement', 'dosage_form' => 'Tablet', 'strength' => null],
            ['generic_name' => 'Calcium carbonate', 'brand_name' => null, 'drug_class' => 'Antacid / calcium supplement', 'dosage_form' => 'Tablet', 'strength' => null],
            ['generic_name' => 'Sodium bicarbonate', 'brand_name' => null, 'drug_class' => 'Urinary alkalinizer / antacid', 'dosage_form' => 'Tablet', 'strength' => null],
            ['generic_name' => 'Glibenclamide', 'brand_name' => null, 'drug_class' => 'Sulfonylurea', 'dosage_form' => 'Tablet', 'strength' => null],
            ['generic_name' => 'Gliclazide', 'brand_name' => null, 'drug_class' => 'Sulfonylurea', 'dosage_form' => 'Tablet', 'strength' => null],
            ['generic_name' => 'Glimepiride', 'brand_name' => null, 'drug_class' => 'Sulfonylurea', 'dosage_form' => 'Tablet', 'strength' => null],
            ['generic_name' => 'Empagliflozin', 'brand_name' => null, 'drug_class' => 'SGLT2 inhibitor', 'dosage_form' => 'Tablet', 'strength' => null],
            ['generic_name' => 'Dapagliflozin', 'brand_name' => null, 'drug_class' => 'SGLT2 inhibitor', 'dosage_form' => 'Tablet', 'strength' => null],
            ['generic_name' => 'Sitagliptin', 'brand_name' => null, 'drug_class' => 'DPP-4 inhibitor', 'dosage_form' => 'Tablet', 'strength' => null],
            ['generic_name' => 'Pioglitazone', 'brand_name' => null, 'drug_class' => 'Thiazolidinedione', 'dosage_form' => 'Tablet', 'strength' => null],
            ['generic_name' => 'Insulin glargine', 'brand_name' => null, 'drug_class' => 'Long-acting insulin', 'dosage_form' => 'Injection', 'strength' => null],
            ['generic_name' => 'Insulin regular', 'brand_name' => null, 'drug_class' => 'Short-acting insulin', 'dosage_form' => 'Injection', 'strength' => null],
            ['generic_name' => 'Pantoprazole', 'brand_name' => null, 'drug_class' => 'Proton pump inhibitor', 'dosage_form' => 'Tablet', 'strength' => null],
            ['generic_name' => 'Esomeprazole', 'brand_name' => null, 'drug_class' => 'Proton pump inhibitor', 'dosage_form' => 'Capsule', 'strength' => null],
            ['generic_name' => 'Famotidine', 'brand_name' => null, 'drug_class' => 'H2 blocker', 'dosage_form' => 'Tablet', 'strength' => null],
            ['generic_name' => 'Sucralfate', 'brand_name' => null, 'drug_class' => 'Mucosal protectant', 'dosage_form' => 'Tablet', 'strength' => null],
            ['generic_name' => 'Aluminium hydroxide', 'brand_name' => null, 'drug_class' => 'Antacid', 'dosage_form' => 'Tablet', 'strength' => null],
            ['generic_name' => 'Magnesium hydroxide', 'brand_name' => null, 'drug_class' => 'Antacid / laxative', 'dosage_form' => 'Tablet', 'strength' => null],
            ['generic_name' => 'Metoclopramide', 'brand_name' => null, 'drug_class' => 'Prokinetic / antiemetic', 'dosage_form' => 'Tablet', 'strength' => null],
            ['generic_name' => 'Ondansetron', 'brand_name' => null, 'drug_class' => 'Antiemetic', 'dosage_form' => 'Tablet', 'strength' => null],
            ['generic_name' => 'Amoxicillin/clavulanic acid', 'brand_name' => null, 'drug_class' => 'Penicillin antibiotic', 'dosage_form' => 'Tablet', 'strength' => null],
            ['generic_name' => 'Penicillin V', 'brand_name' => null, 'drug_class' => 'Penicillin antibiotic', 'dosage_form' => 'Tablet', 'strength' => null],
            ['generic_name' => 'Flucloxacillin', 'brand_name' => null, 'drug_class' => 'Penicillin antibiotic', 'dosage_form' => 'Capsule', 'strength' => null],
            ['generic_name' => 'Cefuroxime', 'brand_name' => null, 'drug_class' => 'Cephalosporin antibiotic', 'dosage_form' => 'Tablet', 'strength' => null],
            ['generic_name' => 'Ceftriaxone', 'brand_name' => null, 'drug_class' => 'Cephalosporin antibiotic', 'dosage_form' => 'Injection', 'strength' => null],
            ['generic_name' => 'Cefixime', 'brand_name' => null, 'drug_class' => 'Cephalosporin antibiotic', 'dosage_form' => 'Tablet', 'strength' => null],
            ['generic_name' => 'Clarithromycin', 'brand_name' => null, 'drug_class' => 'Macrolide antibiotic', 'dosage_form' => 'Tablet', 'strength' => null],
            ['generic_name' => 'Erythromycin', 'brand_name' => null, 'drug_class' => 'Macrolide antibiotic', 'dosage_form' => 'Tablet', 'strength' => null],
            ['generic_name' => 'Levofloxacin', 'brand_name' => null, 'drug_class' => 'Fluoroquinolone antibiotic', 'dosage_form' => 'Tablet', 'strength' => null],
            ['generic_name' => 'Doxycycline', 'brand_name' => null, 'drug_class' => 'Tetracycline antibiotic', 'dosage_form' => 'Capsule', 'strength' => null],
            ['generic_name' => 'Clindamycin', 'brand_name' => null, 'drug_class' => 'Lincosamide antibiotic', 'dosage_form' => 'Capsule', 'strength' => null],
            ['generic_name' => 'Gentamicin', 'brand_name' => null, 'drug_class' => 'Aminoglycoside antibiotic', 'dosage_form' => 'Injection', 'strength' => null],
            ['generic_name' => 'Trimethoprim/sulfamethoxazole', 'brand_name' => null, 'drug_class' => 'Antibiotic combination', 'dosage_form' => 'Tablet', 'strength' => null],
            ['generic_name' => 'Nitrofurantoin', 'brand_name' => null, 'drug_class' => 'Urinary antiseptic antibiotic', 'dosage_form' => 'Capsule', 'strength' => null],
            ['generic_name' => 'Linezolid', 'brand_name' => null, 'drug_class' => 'Oxazolidinone antibiotic', 'dosage_form' => 'Tablet', 'strength' => null],
            ['generic_name' => 'Rifampicin', 'brand_name' => null, 'drug_class' => 'Rifamycin antibiotic', 'dosage_form' => 'Capsule', 'strength' => null],
            ['generic_name' => 'Isoniazid', 'brand_name' => null, 'drug_class' => 'Antitubercular', 'dosage_form' => 'Tablet', 'strength' => null],
            ['generic_name' => 'Pyrazinamide', 'brand_name' => null, 'drug_class' => 'Antitubercular', 'dosage_form' => 'Tablet', 'strength' => null],
            ['generic_name' => 'Ethambutol', 'brand_name' => null, 'drug_class' => 'Antitubercular', 'dosage_form' => 'Tablet', 'strength' => null],
            ['generic_name' => 'Fluconazole', 'brand_name' => null, 'drug_class' => 'Azole antifungal', 'dosage_form' => 'Tablet', 'strength' => null],
            ['generic_name' => 'Itraconazole', 'brand_name' => null, 'drug_class' => 'Azole antifungal', 'dosage_form' => 'Capsule', 'strength' => null],
            ['generic_name' => 'Ketoconazole', 'brand_name' => null, 'drug_class' => 'Azole antifungal', 'dosage_form' => 'Tablet', 'strength' => null],
            ['generic_name' => 'Amphotericin B', 'brand_name' => null, 'drug_class' => 'Polyene antifungal', 'dosage_form' => 'Injection', 'strength' => null],
            ['generic_name' => 'Artemether/lumefantrine', 'brand_name' => null, 'drug_class' => 'Antimalarial', 'dosage_form' => 'Tablet', 'strength' => null],
            ['generic_name' => 'Artesunate', 'brand_name' => null, 'drug_class' => 'Antimalarial', 'dosage_form' => 'Injection', 'strength' => null],
            ['generic_name' => 'Quinine', 'brand_name' => null, 'drug_class' => 'Antimalarial', 'dosage_form' => 'Tablet', 'strength' => null],
            ['generic_name' => 'Naproxen', 'brand_name' => null, 'drug_class' => 'NSAID', 'dosage_form' => 'Tablet', 'strength' => null],
            ['generic_name' => 'Celecoxib', 'brand_name' => null, 'drug_class' => 'COX-2 inhibitor', 'dosage_form' => 'Capsule', 'strength' => null],
            ['generic_name' => 'Tramadol', 'brand_name' => null, 'drug_class' => 'Opioid analgesic', 'dosage_form' => 'Tablet', 'strength' => null],
            ['generic_name' => 'Codeine', 'brand_name' => null, 'drug_class' => 'Opioid analgesic', 'dosage_form' => 'Tablet', 'strength' => null],
            ['generic_name' => 'Morphine', 'brand_name' => null, 'drug_class' => 'Opioid analgesic', 'dosage_form' => 'Injection', 'strength' => null],
            ['generic_name' => 'Prednisone', 'brand_name' => null, 'drug_class' => 'Corticosteroid', 'dosage_form' => 'Tablet', 'strength' => null],
            ['generic_name' => 'Prednisolone', 'brand_name' => null, 'drug_class' => 'Corticosteroid', 'dosage_form' => 'Tablet', 'strength' => null],
            ['generic_name' => 'Dexamethasone', 'brand_name' => null, 'drug_class' => 'Corticosteroid', 'dosage_form' => 'Tablet', 'strength' => null],
            ['generic_name' => 'Hydrocortisone', 'brand_name' => null, 'drug_class' => 'Corticosteroid', 'dosage_form' => 'Tablet', 'strength' => null],
            ['generic_name' => 'Methylprednisolone', 'brand_name' => null, 'drug_class' => 'Corticosteroid', 'dosage_form' => 'Tablet', 'strength' => null],
            ['generic_name' => 'Budesonide', 'brand_name' => null, 'drug_class' => 'Corticosteroid', 'dosage_form' => 'Inhaler', 'strength' => null],
            ['generic_name' => 'Fluticasone', 'brand_name' => null, 'drug_class' => 'Corticosteroid', 'dosage_form' => 'Inhaler', 'strength' => null],
            ['generic_name' => 'Methotrexate', 'brand_name' => null, 'drug_class' => 'Antimetabolite / immunosuppressant', 'dosage_form' => 'Tablet', 'strength' => null],
            ['generic_name' => 'Azathioprine', 'brand_name' => null, 'drug_class' => 'Immunosuppressant', 'dosage_form' => 'Tablet', 'strength' => null],
            ['generic_name' => 'Cyclosporine', 'brand_name' => null, 'drug_class' => 'Calcineurin inhibitor', 'dosage_form' => 'Capsule', 'strength' => null],
            ['generic_name' => 'Tacrolimus', 'brand_name' => null, 'drug_class' => 'Calcineurin inhibitor', 'dosage_form' => 'Capsule', 'strength' => null],
            ['generic_name' => 'Mycophenolate mofetil', 'brand_name' => null, 'drug_class' => 'Immunosuppressant', 'dosage_form' => 'Tablet', 'strength' => null],
            ['generic_name' => 'Tenofovir disoproxil fumarate', 'brand_name' => null, 'drug_class' => 'NRTI', 'dosage_form' => 'Tablet', 'strength' => null],
            ['generic_name' => 'Lamivudine', 'brand_name' => null, 'drug_class' => 'NRTI', 'dosage_form' => 'Tablet', 'strength' => null],
            ['generic_name' => 'Dolutegravir', 'brand_name' => null, 'drug_class' => 'Integrase inhibitor', 'dosage_form' => 'Tablet', 'strength' => null],
            ['generic_name' => 'Efavirenz', 'brand_name' => null, 'drug_class' => 'NNRTI', 'dosage_form' => 'Capsule', 'strength' => null],
            ['generic_name' => 'Nevirapine', 'brand_name' => null, 'drug_class' => 'NNRTI', 'dosage_form' => 'Tablet', 'strength' => null],
            ['generic_name' => 'Zidovudine', 'brand_name' => null, 'drug_class' => 'NRTI', 'dosage_form' => 'Capsule', 'strength' => null],
            ['generic_name' => 'Abacavir', 'brand_name' => null, 'drug_class' => 'NRTI', 'dosage_form' => 'Tablet', 'strength' => null],
            ['generic_name' => 'Emtricitabine', 'brand_name' => null, 'drug_class' => 'NRTI', 'dosage_form' => 'Capsule', 'strength' => null],
            ['generic_name' => 'Atazanavir', 'brand_name' => null, 'drug_class' => 'Protease inhibitor', 'dosage_form' => 'Capsule', 'strength' => null],
            ['generic_name' => 'Darunavir', 'brand_name' => null, 'drug_class' => 'Protease inhibitor', 'dosage_form' => 'Tablet', 'strength' => null],
            ['generic_name' => 'Lopinavir', 'brand_name' => null, 'drug_class' => 'Protease inhibitor', 'dosage_form' => 'Tablet', 'strength' => null],
            ['generic_name' => 'Ritonavir', 'brand_name' => null, 'drug_class' => 'Protease inhibitor / booster', 'dosage_form' => 'Tablet', 'strength' => null],
            ['generic_name' => 'Rilpivirine', 'brand_name' => null, 'drug_class' => 'NNRTI', 'dosage_form' => 'Tablet', 'strength' => null],
            ['generic_name' => 'Bictegravir', 'brand_name' => null, 'drug_class' => 'Integrase inhibitor', 'dosage_form' => 'Tablet', 'strength' => null],
            ['generic_name' => 'Cobicistat', 'brand_name' => null, 'drug_class' => 'Pharmacokinetic booster', 'dosage_form' => 'Tablet', 'strength' => null],
            ['generic_name' => 'Sodium valproate', 'brand_name' => null, 'drug_class' => 'Antiepileptic', 'dosage_form' => 'Tablet', 'strength' => null],
            ['generic_name' => 'Phenobarbital', 'brand_name' => null, 'drug_class' => 'Antiepileptic', 'dosage_form' => 'Tablet', 'strength' => null],
            ['generic_name' => 'Lamotrigine', 'brand_name' => null, 'drug_class' => 'Antiepileptic', 'dosage_form' => 'Tablet', 'strength' => null],
            ['generic_name' => 'Fluoxetine', 'brand_name' => null, 'drug_class' => 'SSRI antidepressant', 'dosage_form' => 'Capsule', 'strength' => null],
            ['generic_name' => 'Sertraline', 'brand_name' => null, 'drug_class' => 'SSRI antidepressant', 'dosage_form' => 'Tablet', 'strength' => null],
            ['generic_name' => 'Amitriptyline', 'brand_name' => null, 'drug_class' => 'Tricyclic antidepressant', 'dosage_form' => 'Tablet', 'strength' => null],
            ['generic_name' => 'Haloperidol', 'brand_name' => null, 'drug_class' => 'Antipsychotic', 'dosage_form' => 'Tablet', 'strength' => null],
            ['generic_name' => 'Quetiapine', 'brand_name' => null, 'drug_class' => 'Antipsychotic', 'dosage_form' => 'Tablet', 'strength' => null],
            ['generic_name' => 'Salbutamol', 'brand_name' => null, 'drug_class' => 'Short-acting beta agonist', 'dosage_form' => 'Inhaler', 'strength' => null],
            ['generic_name' => 'Ipratropium', 'brand_name' => null, 'drug_class' => 'Anticholinergic bronchodilator', 'dosage_form' => 'Inhaler', 'strength' => null],
            ['generic_name' => 'Theophylline', 'brand_name' => null, 'drug_class' => 'Methylxanthine bronchodilator', 'dosage_form' => 'Tablet', 'strength' => null],
        ];

        foreach ($drugs as $drug) {
            Drug::updateOrCreate(
                ['generic_name' => $drug['generic_name']],
                [
                    'brand_name' => $drug['brand_name'],
                    'drug_class' => $drug['drug_class'],
                    'dosage_form' => $drug['dosage_form'],
                    'strength' => $drug['strength'],
                    'description' => null,
                    'contraindications' => null,
                    'warnings' => null,
                    'storage_information' => null,
                    'is_active' => true,
                ]
            );
        }
    }
}
