<?php

namespace Database\Seeders;

use App\Models\Drug;
use App\Models\DrugInteraction;
use App\Models\InteractionSeverity;
use App\Services\DrugPairNormalizer;
use Illuminate\Database\Seeder;

class DrugInteractionSeeder extends Seeder
{
    /**
     * Clinical content requires pharmacist review before use.
     */
    public function run(): void
    {
        $normalizer = new DrugPairNormalizer();

        $drugs = Drug::query()
            ->whereIn('generic_name', [
                'Warfarin',
                'Ibuprofen',
                'Aspirin',
                'Metronidazole',
                'Ciprofloxacin',
                'Enalapril',
                'Losartan',
                'Clopidogrel',
                'Omeprazole',
                'Carbamazepine',
                'Phenytoin',
                'Simvastatin',
                'Azithromycin',
                'Rifampicin',
                'Fluconazole',
                'Clarithromycin',
                'Atorvastatin',
                'Trimethoprim/sulfamethoxazole',
                'Digoxin',
                'Amiodarone',
                'Verapamil',
                'Furosemide',
                'Spironolactone',
                'Lisinopril',
                'Dolutegravir',
                'Calcium carbonate',
                'Linezolid',
                'Fluoxetine',
                'Prednisolone',
                'Cyclosporine',
            ])
            ->get()
            ->keyBy('generic_name');

        $severities = InteractionSeverity::query()
            ->get()
            ->keyBy('slug');

        $records = [
            [
                'drug_a' => 'Warfarin',
                'drug_b' => 'Ibuprofen',
                'severity' => 'major',
                'mechanism' => 'NSAID therapy can increase bleeding risk when used with anticoagulants.',
                'clinical_effect' => 'Increased risk of gastrointestinal bleeding and other hemorrhagic events.',
                'management' => 'Avoid if possible. Consider alternative analgesics and assess bleeding risk closely if combined.',
                'monitoring_advice' => 'Monitor for bruising, melena, hematuria, and changes in INR when clinically appropriate.',
                'evidence_level' => 'High',
                'reference' => 'DailyMed warfarin label; DailyMed ibuprofen label. NSAIDs increase bleeding risk with warfarin.',
                'notes' => null,
            ],
            [
                'drug_a' => 'Warfarin',
                'drug_b' => 'Aspirin',
                'severity' => 'major',
                'mechanism' => 'Combined anticoagulant and antiplatelet effects increase bleeding risk.',
                'clinical_effect' => 'Higher likelihood of major bleeding, especially gastrointestinal bleeding.',
                'management' => 'Use only when clearly indicated and with careful risk-benefit review.',
                'monitoring_advice' => 'Monitor for bleeding signs and reassess need for dual therapy regularly.',
                'evidence_level' => 'High',
                'reference' => 'DailyMed warfarin label; DailyMed aspirin label. Aspirin increases bleeding risk with anticoagulants.',
                'notes' => null,
            ],
            [
                'drug_a' => 'Warfarin',
                'drug_b' => 'Metronidazole',
                'severity' => 'contraindicated',
                'mechanism' => 'Metronidazole can inhibit warfarin metabolism and increase anticoagulant effect.',
                'clinical_effect' => 'INR elevation and increased bleeding risk.',
                'management' => 'Avoid when possible. If unavoidable, intensify INR monitoring and adjust anticoagulation as needed.',
                'monitoring_advice' => 'Check INR closely and monitor for bleeding.',
                'evidence_level' => 'High',
                'reference' => 'DailyMed metronidazole label. Metronidazole potentiates warfarin and prolongs PT/INR.',
                'notes' => null,
            ],
            [
                'drug_a' => 'Warfarin',
                'drug_b' => 'Ciprofloxacin',
                'severity' => 'major',
                'mechanism' => 'Ciprofloxacin may enhance warfarin effect through metabolic and gut-flora related mechanisms.',
                'clinical_effect' => 'Possible INR increase and bleeding risk.',
                'management' => 'Use caution and monitor anticoagulation more frequently during coadministration.',
                'monitoring_advice' => 'Monitor INR and bleeding symptoms.',
                'evidence_level' => 'Moderate to high',
                'reference' => 'DailyMed ciprofloxacin label. Fluoroquinolones may increase anticoagulant effect and require INR monitoring.',
                'notes' => null,
            ],
            [
                'drug_a' => 'Enalapril',
                'drug_b' => 'Losartan',
                'severity' => 'major',
                'mechanism' => 'Dual renin-angiotensin system blockade can increase adverse renal and potassium effects.',
                'clinical_effect' => 'Risk of hypotension, hyperkalemia, and reduced renal function.',
                'management' => 'Generally avoid routine combination use unless specifically justified and closely supervised.',
                'monitoring_advice' => 'Monitor blood pressure, serum potassium, and renal function.',
                'evidence_level' => 'High',
                'reference' => 'DailyMed enalapril label. Dual renin-angiotensin system blockade increases hypotension, hyperkalemia, and renal impairment.',
                'notes' => null,
            ],
            [
                'drug_a' => 'Clopidogrel',
                'drug_b' => 'Omeprazole',
                'severity' => 'moderate',
                'mechanism' => 'Omeprazole may reduce clopidogrel activation via CYP2C19 inhibition.',
                'clinical_effect' => 'Potential reduction in antiplatelet effect.',
                'management' => 'Consider an alternative acid-suppressing therapy when appropriate or review the indication carefully.',
                'monitoring_advice' => 'Monitor for reduced antiplatelet response when clinically relevant.',
                'evidence_level' => 'Moderate',
                'reference' => 'DailyMed clopidogrel label. Avoid concomitant omeprazole or esomeprazole because they reduce clopidogrel activation.',
                'notes' => null,
            ],
            [
                'drug_a' => 'Carbamazepine',
                'drug_b' => 'Warfarin',
                'severity' => 'major',
                'mechanism' => 'Carbamazepine may induce warfarin metabolism and lower anticoagulant effect.',
                'clinical_effect' => 'Reduced INR and possible loss of anticoagulation control.',
                'management' => 'Monitor INR carefully and anticipate warfarin dose adjustment if needed.',
                'monitoring_advice' => 'Monitor INR more frequently after carbamazepine changes.',
                'evidence_level' => 'High',
                'reference' => 'DailyMed warfarin labeling and carbamazepine interaction data. Enzyme induction can reduce warfarin effect.',
                'notes' => null,
            ],
            [
                'drug_a' => 'Phenytoin',
                'drug_b' => 'Warfarin',
                'severity' => 'major',
                'mechanism' => 'Bidirectional interaction can alter both anticoagulant and anticonvulsant exposure.',
                'clinical_effect' => 'Unpredictable INR and phenytoin concentrations.',
                'management' => 'Use with caution and monitor both therapies closely.',
                'monitoring_advice' => 'Monitor INR and phenytoin effects/levels when available.',
                'evidence_level' => 'Moderate to high',
                'reference' => 'DailyMed phenytoin and warfarin labels. PT/INR responses may rise or fall with coadministration.',
                'notes' => null,
            ],
            [
                'drug_a' => 'Simvastatin',
                'drug_b' => 'Azithromycin',
                'severity' => 'moderate',
                'mechanism' => 'Macrolide antibiotics may raise statin exposure, although azithromycin is a lower-risk macrolide than clarithromycin or erythromycin.',
                'clinical_effect' => 'Potential increase in statin adverse effects including myopathy.',
                'management' => 'Use caution and monitor for muscle pain or weakness.',
                'monitoring_advice' => 'Monitor for myopathy symptoms and consider temporary statin interruption if clinically appropriate.',
                'evidence_level' => 'Moderate',
                'reference' => 'Medsafe statin interaction guidance; azithromycin is a lower-risk macrolide but case reports of myopathy exist.',
                'notes' => null,
            ],
            [
                'drug_a' => 'Ibuprofen',
                'drug_b' => 'Aspirin',
                'severity' => 'moderate',
                'mechanism' => 'Ibuprofen can interfere with aspirin\'s antiplatelet effect and add GI toxicity.',
                'clinical_effect' => 'Potential reduction in aspirin cardioprotection and increased bleeding or GI irritation.',
                'management' => 'Avoid frequent concurrent use when possible or separate timing if advised by a clinician.',
                'monitoring_advice' => 'Monitor for GI bleeding and review antiplatelet benefit if combined.',
                'evidence_level' => 'Moderate',
                'reference' => 'DailyMed ibuprofen label. Ibuprofen can interfere with aspirin antiplatelet activity; timing depends on aspirin formulation.',
                'notes' => null,
            ],
            [
                'drug_a' => 'Metronidazole',
                'drug_b' => 'Phenytoin',
                'severity' => 'moderate',
                'mechanism' => 'Metronidazole can alter phenytoin exposure in some patients.',
                'clinical_effect' => 'Possible phenytoin toxicity or altered seizure control.',
                'management' => 'Monitor closely if used together and review seizure symptoms or adverse effects.',
                'monitoring_advice' => 'Monitor for neurologic toxicity and seizure control.',
                'evidence_level' => 'Moderate',
                'reference' => 'DailyMed metronidazole label. Phenytoin may accelerate metronidazole elimination and impaired phenytoin clearance has also been reported.',
                'notes' => null,
            ],
            [
                'drug_a' => 'Ciprofloxacin',
                'drug_b' => 'Phenytoin',
                'severity' => 'moderate',
                'mechanism' => 'Fluoroquinolones can unpredictably affect phenytoin concentrations and seizure threshold.',
                'clinical_effect' => 'Possible changes in phenytoin levels and seizure control.',
                'management' => 'Use caution and monitor neurological status and phenytoin response.',
                'monitoring_advice' => 'Monitor for breakthrough seizures or toxicity.',
                'evidence_level' => 'Moderate',
                'reference' => 'DailyMed ciprofloxacin label. Phenytoin serum levels may increase or decrease with ciprofloxacin.',
                'notes' => null,
            ],
            [
                'drug_a' => 'Enalapril',
                'drug_b' => 'Ibuprofen',
                'severity' => 'moderate',
                'mechanism' => 'NSAIDs can reduce antihypertensive response and contribute to renal effects with ACE inhibitors.',
                'clinical_effect' => 'Reduced blood pressure control and increased renal risk in susceptible patients.',
                'management' => 'Use caution, especially in older adults or those with kidney disease or dehydration.',
                'monitoring_advice' => 'Monitor blood pressure, renal function, and hydration status.',
                'evidence_level' => 'Moderate',
                'reference' => 'DailyMed enalapril label. NSAIDs may reduce ACE inhibitor effect and worsen renal function in susceptible patients.',
                'notes' => null,
            ],
            [
                'drug_a' => 'Warfarin',
                'drug_b' => 'Rifampicin',
                'severity' => 'major',
                'mechanism' => 'Rifampicin strongly induces hepatic drug-metabolizing enzymes and can reduce warfarin exposure.',
                'clinical_effect' => 'Reduced anticoagulant effect and lower INR.',
                'management' => 'Avoid if possible or anticipate a substantial warfarin dose increase with close INR-guided adjustment.',
                'monitoring_advice' => 'Monitor INR frequently during rifampicin initiation, continuation, and discontinuation.',
                'evidence_level' => 'High',
                'reference' => 'DailyMed rifampin label. Rifampin decreases warfarin exposure and requires close PT/INR monitoring.',
                'notes' => null,
            ],
            [
                'drug_a' => 'Warfarin',
                'drug_b' => 'Fluconazole',
                'severity' => 'major',
                'mechanism' => 'Fluconazole inhibits CYP2C9 and can increase warfarin exposure.',
                'clinical_effect' => 'Increased PT/INR and bleeding risk.',
                'management' => 'Use with caution and adjust warfarin based on INR response if the combination cannot be avoided.',
                'monitoring_advice' => 'Monitor PT/INR closely during and shortly after treatment.',
                'evidence_level' => 'High',
                'reference' => 'DailyMed fluconazole label. Fluconazole increases prothrombin time in coumarin-treated patients.',
                'notes' => null,
            ],
            [
                'drug_a' => 'Warfarin',
                'drug_b' => 'Trimethoprim/sulfamethoxazole',
                'severity' => 'major',
                'mechanism' => 'Trimethoprim/sulfamethoxazole can prolong prothrombin time in patients receiving warfarin.',
                'clinical_effect' => 'Higher INR and increased bleeding risk.',
                'management' => 'Avoid when possible. If unavoidable, increase INR surveillance and adjust warfarin.',
                'monitoring_advice' => 'Monitor INR and bleeding symptoms closely.',
                'evidence_level' => 'High',
                'reference' => 'DailyMed trimethoprim/sulfamethoxazole label. Warfarin coadministration requires PT/INR reassessment.',
                'notes' => null,
            ],
            [
                'drug_a' => 'Clarithromycin',
                'drug_b' => 'Warfarin',
                'severity' => 'major',
                'mechanism' => 'Clarithromycin can raise warfarin exposure and increase anticoagulant effect.',
                'clinical_effect' => 'Serious hemorrhage risk with significant INR elevation.',
                'management' => 'Avoid if possible or monitor INR very frequently when the combination is necessary.',
                'monitoring_advice' => 'Monitor INR and signs of bleeding.',
                'evidence_level' => 'High',
                'reference' => 'DailyMed clarithromycin label. Clarithromycin with warfarin can markedly increase INR and bleeding risk.',
                'notes' => null,
            ],
            [
                'drug_a' => 'Clarithromycin',
                'drug_b' => 'Simvastatin',
                'severity' => 'contraindicated',
                'mechanism' => 'Clarithromycin strongly inhibits CYP3A4 and markedly increases simvastatin exposure.',
                'clinical_effect' => 'Increased risk of myopathy and rhabdomyolysis.',
                'management' => 'Do not use together. Suspend simvastatin during clarithromycin therapy if clarithromycin cannot be avoided.',
                'monitoring_advice' => 'Monitor for muscle pain, weakness, and dark urine if exposure occurred.',
                'evidence_level' => 'High',
                'reference' => 'DailyMed clarithromycin label. Concomitant use with simvastatin is contraindicated.',
                'notes' => null,
            ],
            [
                'drug_a' => 'Clarithromycin',
                'drug_b' => 'Atorvastatin',
                'severity' => 'major',
                'mechanism' => 'Clarithromycin can increase atorvastatin exposure through CYP3A4 inhibition.',
                'clinical_effect' => 'Higher risk of statin-associated myopathy.',
                'management' => 'Use the lowest atorvastatin dose possible or consider an alternative antibiotic if clinically appropriate.',
                'monitoring_advice' => 'Monitor for myopathy symptoms and review dose limits.',
                'evidence_level' => 'High',
                'reference' => 'DailyMed clarithromycin label. Exercise caution with atorvastatin; lower doses are recommended if coadministration is unavoidable.',
                'notes' => null,
            ],
            [
                'drug_a' => 'Digoxin',
                'drug_b' => 'Amiodarone',
                'severity' => 'major',
                'mechanism' => 'Amiodarone increases digoxin concentrations by reducing clearance.',
                'clinical_effect' => 'Digoxin toxicity with bradycardia, nausea, visual changes, or arrhythmia.',
                'management' => 'Reduce digoxin dose or discontinue if appropriate and review the need for digoxin therapy.',
                'monitoring_advice' => 'Monitor serum digoxin concentration, heart rate, and toxicity signs.',
                'evidence_level' => 'High',
                'reference' => 'DailyMed digoxin and amiodarone labels. Amiodarone raises digoxin concentration; dose reduction and monitoring are recommended.',
                'notes' => null,
            ],
            [
                'drug_a' => 'Digoxin',
                'drug_b' => 'Verapamil',
                'severity' => 'major',
                'mechanism' => 'Verapamil can increase digoxin concentration and potentiate bradycardia.',
                'clinical_effect' => 'Increased risk of digoxin toxicity and AV block.',
                'management' => 'Use with caution, consider lowering digoxin dose, and review heart rate control.',
                'monitoring_advice' => 'Monitor digoxin level, pulse, ECG, and toxicity symptoms.',
                'evidence_level' => 'High',
                'reference' => 'DailyMed digoxin label. Verapamil increases digoxin concentration substantially.',
                'notes' => null,
            ],
            [
                'drug_a' => 'Digoxin',
                'drug_b' => 'Furosemide',
                'severity' => 'moderate',
                'mechanism' => 'Furosemide can cause potassium depletion, which increases susceptibility to digoxin toxicity.',
                'clinical_effect' => 'Greater risk of digitalis toxicity and arrhythmia in hypokalemic patients.',
                'management' => 'Use cautiously and correct electrolyte abnormalities promptly.',
                'monitoring_advice' => 'Monitor potassium, magnesium, renal function, and digoxin toxicity signs.',
                'evidence_level' => 'High',
                'reference' => 'DailyMed furosemide and digoxin labels. Potassium depletion from loop diuretics can exaggerate digitalis toxicity.',
                'notes' => null,
            ],
            [
                'drug_a' => 'Lisinopril',
                'drug_b' => 'Spironolactone',
                'severity' => 'major',
                'mechanism' => 'Both medicines increase potassium and can amplify hyperkalemia risk.',
                'clinical_effect' => 'Hyperkalemia and possible renal function decline.',
                'management' => 'Use only when clinically justified and monitor potassium very closely.',
                'monitoring_advice' => 'Check serum potassium and renal function after initiation and dose changes.',
                'evidence_level' => 'High',
                'reference' => 'DailyMed lisinopril and spironolactone labels. Potassium-sparing diuretics increase hyperkalemia risk with ACE inhibitors.',
                'notes' => null,
            ],
            [
                'drug_a' => 'Lisinopril',
                'drug_b' => 'Trimethoprim/sulfamethoxazole',
                'severity' => 'major',
                'mechanism' => 'Trimethoprim can contribute to hyperkalemia when combined with ACE inhibitors.',
                'clinical_effect' => 'Hyperkalemia, especially in older adults or those with renal impairment.',
                'management' => 'Avoid if reasonable alternatives exist; otherwise monitor potassium and renal function closely.',
                'monitoring_advice' => 'Monitor serum potassium and renal function during treatment.',
                'evidence_level' => 'Moderate to high',
                'reference' => 'DailyMed trimethoprim/sulfamethoxazole label and lisinopril label. Hyperkalemia has been reported with ACE inhibitors.',
                'notes' => null,
            ],
            [
                'drug_a' => 'Dolutegravir',
                'drug_b' => 'Calcium carbonate',
                'severity' => 'moderate',
                'mechanism' => 'Calcium can reduce dolutegravir absorption by chelation.',
                'clinical_effect' => 'Reduced dolutegravir exposure and potential loss of antiviral effect.',
                'management' => 'Separate administration or take with food when the product label allows.',
                'monitoring_advice' => 'Counsel on dosing separation and monitor HIV control as clinically appropriate.',
                'evidence_level' => 'High',
                'reference' => 'DailyMed Tivicay label. Antacids containing calcium, magnesium, or aluminum require spacing from dolutegravir.',
                'notes' => null,
            ],
            [
                'drug_a' => 'Linezolid',
                'drug_b' => 'Fluoxetine',
                'severity' => 'major',
                'mechanism' => 'Linezolid has MAOI activity and can precipitate serotonin toxicity with SSRIs.',
                'clinical_effect' => 'Serotonin syndrome, which can be severe or fatal.',
                'management' => 'Avoid if possible. If linezolid is essential, stop the serotonergic antidepressant and monitor closely.',
                'monitoring_advice' => 'Monitor for agitation, hyperreflexia, fever, autonomic instability, and mental status changes.',
                'evidence_level' => 'High',
                'reference' => 'DailyMed linezolid label. Serotonin syndrome has been reported with serotonergic antidepressants, including SSRIs.',
                'notes' => null,
            ],
            [
                'drug_a' => 'Fluconazole',
                'drug_b' => 'Phenytoin',
                'severity' => 'major',
                'mechanism' => 'Fluconazole inhibits phenytoin metabolism and increases phenytoin exposure.',
                'clinical_effect' => 'Phenytoin toxicity, nystagmus, ataxia, and CNS adverse effects.',
                'management' => 'Use with caution and adjust phenytoin based on levels and clinical response.',
                'monitoring_advice' => 'Monitor phenytoin concentrations and neurologic toxicity.',
                'evidence_level' => 'High',
                'reference' => 'DailyMed fluconazole label. Fluconazole increases phenytoin plasma concentrations.',
                'notes' => null,
            ],
            [
                'drug_a' => 'Fluconazole',
                'drug_b' => 'Cyclosporine',
                'severity' => 'major',
                'mechanism' => 'Fluconazole can significantly increase cyclosporine concentrations.',
                'clinical_effect' => 'Nephrotoxicity and cyclosporine toxicity.',
                'management' => 'Use only with close specialist supervision and dose adjustment if needed.',
                'monitoring_advice' => 'Monitor cyclosporine concentrations and serum creatinine.',
                'evidence_level' => 'High',
                'reference' => 'DailyMed fluconazole label. Cyclosporine concentrations and creatinine should be monitored closely.',
                'notes' => null,
            ],
            [
                'drug_a' => 'Rifampicin',
                'drug_b' => 'Dolutegravir',
                'severity' => 'major',
                'mechanism' => 'Rifampicin induces metabolism and lowers dolutegravir exposure.',
                'clinical_effect' => 'Reduced antiretroviral exposure and risk of virologic failure.',
                'management' => 'Use the dose adjustment recommended in the product label or an alternative regimen approved by HIV guidelines.',
                'monitoring_advice' => 'Monitor adherence and virologic response closely.',
                'evidence_level' => 'High',
                'reference' => 'DailyMed Dovato and Tivicay labels. Rifampin requires additional dolutegravir dosing or other label-directed adjustment.',
                'notes' => null,
            ],
            [
                'drug_a' => 'Rifampicin',
                'drug_b' => 'Prednisolone',
                'severity' => 'moderate',
                'mechanism' => 'Rifampicin induces corticosteroid metabolism and can lower prednisolone exposure.',
                'clinical_effect' => 'Reduced corticosteroid effect.',
                'management' => 'Review need for dose adjustment or alternative therapy during rifampicin treatment.',
                'monitoring_advice' => 'Monitor clinical response to corticosteroid therapy.',
                'evidence_level' => 'High',
                'reference' => 'DailyMed rifampin label. Rifampin decreases prednisolone exposure.',
                'notes' => null,
            ],
            [
                'drug_a' => 'Rifampicin',
                'drug_b' => 'Digoxin',
                'severity' => 'moderate',
                'mechanism' => 'Rifampicin can lower digoxin exposure by increasing clearance.',
                'clinical_effect' => 'Reduced digoxin effect.',
                'management' => 'Monitor serum digoxin concentrations and clinical response; dosage increase may be needed.',
                'monitoring_advice' => 'Check digoxin concentration and symptoms after rifampicin is started or stopped.',
                'evidence_level' => 'High',
                'reference' => 'DailyMed rifampin label. Digoxin concentrations fall and dose increase may be required.',
                'notes' => null,
            ],
            [
                'drug_a' => 'Clarithromycin',
                'drug_b' => 'Warfarin',
                'severity' => 'major',
                'mechanism' => 'Clarithromycin can raise warfarin exposure and increase anticoagulant effect.',
                'clinical_effect' => 'Serious hemorrhage risk with significant INR elevation.',
                'management' => 'Avoid if possible or monitor INR very frequently when the combination is necessary.',
                'monitoring_advice' => 'Monitor INR and signs of bleeding.',
                'evidence_level' => 'High',
                'reference' => 'DailyMed clarithromycin label. Clarithromycin with warfarin can markedly increase INR and bleeding risk.',
                'notes' => null,
            ],
            [
                'drug_a' => 'Clarithromycin',
                'drug_b' => 'Simvastatin',
                'severity' => 'contraindicated',
                'mechanism' => 'Clarithromycin strongly inhibits CYP3A4 and markedly increases simvastatin exposure.',
                'clinical_effect' => 'Increased risk of myopathy and rhabdomyolysis.',
                'management' => 'Do not use together. Suspend simvastatin during clarithromycin therapy if clarithromycin cannot be avoided.',
                'monitoring_advice' => 'Monitor for muscle pain, weakness, and dark urine if exposure occurred.',
                'evidence_level' => 'High',
                'reference' => 'DailyMed clarithromycin label. Concomitant use with simvastatin is contraindicated.',
                'notes' => null,
            ],
            [
                'drug_a' => 'Clarithromycin',
                'drug_b' => 'Atorvastatin',
                'severity' => 'major',
                'mechanism' => 'Clarithromycin can increase atorvastatin exposure through CYP3A4 inhibition.',
                'clinical_effect' => 'Higher risk of statin-associated myopathy.',
                'management' => 'Use the lowest atorvastatin dose possible or consider an alternative antibiotic if clinically appropriate.',
                'monitoring_advice' => 'Monitor for myopathy symptoms and review dose limits.',
                'evidence_level' => 'High',
                'reference' => 'DailyMed clarithromycin label. Exercise caution with atorvastatin; lower doses are recommended if coadministration is unavoidable.',
                'notes' => null,
            ],
            [
                'drug_a' => 'Digoxin',
                'drug_b' => 'Furosemide',
                'severity' => 'moderate',
                'mechanism' => 'Furosemide can cause potassium depletion, which increases susceptibility to digoxin toxicity.',
                'clinical_effect' => 'Greater risk of digitalis toxicity and arrhythmia in hypokalemic patients.',
                'management' => 'Use cautiously and correct electrolyte abnormalities promptly.',
                'monitoring_advice' => 'Monitor potassium, magnesium, renal function, and digoxin toxicity signs.',
                'evidence_level' => 'High',
                'reference' => 'DailyMed furosemide and digoxin labels. Potassium depletion from loop diuretics can exaggerate digitalis toxicity.',
                'notes' => null,
            ],
        ];

        foreach ($records as $record) {
            $drugOne = $drugs->get($record['drug_a']);
            $drugTwo = $drugs->get($record['drug_b']);

            if (! $drugOne || ! $drugTwo) {
                continue;
            }

            [$drugAId, $drugBId] = $normalizer->normalize($drugOne->id, $drugTwo->id);

            DrugInteraction::updateOrCreate(
                [
                    'drug_a_id' => $drugAId,
                    'drug_b_id' => $drugBId,
                ],
                [
                    'interaction_severity_id' => $severities->get($record['severity'])?->id,
                    'mechanism' => $record['mechanism'],
                    'clinical_effect' => $record['clinical_effect'],
                    'management' => $record['management'],
                    'monitoring_advice' => $record['monitoring_advice'],
                    'evidence_level' => $record['evidence_level'],
                    'reference' => $record['reference'],
                    'notes' => $record['notes'],
                    'is_active' => true,
                ]
            );
        }
    }
}
